### ISSUE TITLE
Running against files with non UTF-8 characters results in UnicodeErrors

### ISSUE THREAD

**Issue by david-vankampen** [pocc/pre-commit-hooks#21]
```
Traceback (most recent call last):
  File "/home/dave/.cache/pre-commit/repov7j0xgwa/py_env-python3.8/bin/uncrustify-hook", line 8, in <module>
    sys.exit(main())
  File "/home/dave/.cache/pre-commit/repov7j0xgwa/py_env-python3.8/lib/python3.8/site-packages/hooks/uncrustify.py", line 53, in main
    cmd.run()
  File "/home/dave/.cache/pre-commit/repov7j0xgwa/py_env-python3.8/lib/python3.8/site-packages/hooks/uncrustify.py", line 45, in run
    self.compare_to_formatted(filename)
  File "/home/dave/.cache/pre-commit/repov7j0xgwa/py_env-python3.8/lib/python3.8/site-packages/hooks/utils.py", line 164, in compare_to_formatted
    actual = self.get_filelines(filename)
  File "/home/dave/.cache/pre-commit/repov7j0xgwa/py_env-python3.8/lib/python3.8/site-packages/hooks/utils.py", line 203, in get_filelines
    return str(filetext, encoding="utf-8").split("\n")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 631: invalid start byte
```

Perhaps an additional parameter in the yaml file? It can default to UTF-8, but allow the user to configure it if they want something else?

**Comment by pocc** [comment]
What should expected behavior be here? For comparison, diff is pretty unhelpful for your `0x92` and adjacent `0x93`:

```
diff <( echo "92" | xxd -p -r  ) <( echo "93" | xxd -p -r )
1c1
< �
\ No newline at end of file
---
> �
\ No newline at end of file
```

Perhaps an option to compare hexdumps instead of text?

**Comment by pocc** [comment]
Can you confirm that the issue is resolved? I'm no longer decoding everything as a python string.

**Comment by david-vankampen** [comment]
Confirmed.  When I change rev to 0f0886e19bcdedf03c75e9b7918476ec2305ae37 uncrustify gets through the whole codebase, when I change it back to `python` , I get the UnicodeError and it bails out early.  Thanks a lot!
