### ISSUE TITLE
Uncrustify hook doesn't allow you to specify uncrustify commandline arguments. 

### ISSUE THREAD

**Issue by bgianfo** [pocc/pre-commit-hooks#34]
I'm trying to use the uncrustify hook, but if you try to specify a language or configuration file, the parser seems to think they are file names instead of arguments? 

Config file:
```yaml
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.1.1
    hooks:
      - id: uncrustify
        args: ["-l CPP", "-c build/uncrustify.cfg", "--replace" ]
```

Example error call stack:
```
[INFO] Stashing unstaged files to C:\Users\test\.cache\pre-commit\patch1629754966-43936.
uncrustify...............................................................Failed
- hook id: uncrustify
- duration: 0.31s
- exit code: 1

Traceback (most recent call last):
  File "c:\users\test\scoop\apps\python\3.9.6\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\test\scoop\apps\python\3.9.6\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\test\.cache\pre-commit\repo3sfmc84z\py_env-default\Scripts\uncrustify-hook.EXE\__main__.py", line 7, in <module>
  File "C:\Users\test\.cache\pre-commit\repo3sfmc84z\py_env-default\lib\site-packages\hooks\uncrustify.py", line 55, in main
    cmd.run()
  File "C:\Users\test\.cache\pre-commit\repo3sfmc84z\py_env-default\lib\site-packages\hooks\uncrustify.py", line 47, in run
    self.compare_to_formatted(filename)
  File "C:\Users\test\.cache\pre-commit\repo3sfmc84z\py_env-default\lib\site-packages\hooks\utils.py", line 164, in compare_to_formatted
    actual = self.get_filelines(filename)
  File "C:\Users\test\.cache\pre-commit\repo3sfmc84z\py_env-default\lib\site-packages\hooks\utils.py", line 201, in get_filelines
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '-l CPP'
```

**Comment by bgianfo** [comment]
I also validated that the behavior is the same if I use latest master.

**Comment by pocc** [comment]
I've been able to replicate this. I'll look into it.

**Comment by pocc** [comment]
Fixed with v1.1.3. Please try it and tell me if it works for you.

**Comment by bgianfo** [comment]
Sorry for the slow response, I tried I can confirm this specific bug is now fixed.

I'm not sure if it's related, but I'm having trouble now having uncrustify actually run againsts files I change with the hook.
I am debugging in bits when I have time. If I find out what's and it's a bug, I'll open another issue.

Thanks for fixing this!

**Comment by pocc** [comment]
If you can post the breaking file and the options, I can add it to my test suite. Please keep in mind that you should not have spaces in your argument strings (that was one of the problems in your initial post).
